# Generated by Django 5.2.8 on 2026-08-18 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_userpreference_budget_range_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='what_do_you_dress_for',
            field=models.JSONField(blank=True, default=list, help_text='List of dress for options from DRESS_FOR_CHOICES', verbose_name='what do you dress for'),
        ),
    ]
