# Generated by Django 5.2.8 on 2026-09-09 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_userpreference_what_do_you_dress_for"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="password_reset_verified",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether user has verified OTP for password reset",
                verbose_name="password reset verified",
            ),
        ),
    ]
