# Generated by Django 5.2.8 on 2026-09-14 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_user_password_reset_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="referral_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Unique referral code for sharing profile and inviting friends",
                max_length=20,
                null=True,
                unique=True,
                verbose_name="referral code",
            ),
        ),
        migrations.CreateModel(
            name="ClosetPointTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("share_look", "Share a Look (+120)"),
                            ("invite_friend", "Invite Friends (+200)"),
                            ("make_purchase", "Make a Purchase (+200)"),
                            ("add_closet_item", "Add to Closet (+50)"),
                            ("custom_reward", "Custom Reward"),
                            ("redeem_reward", "Redeem Reward"),
                        ],
                        max_length=30,
                        verbose_name="action type",
                    ),
                ),
                ("points", models.IntegerField(verbose_name="points")),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="description"),
                ),
                (
                    "reference_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="reference id",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="expires at"
                    ),
                ),
                (
                    "is_expired",
                    models.BooleanField(default=False, verbose_name="is expired"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="point_transactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "closet point transaction",
                "verbose_name_plural": "closet point transactions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserPointSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_points",
                    models.PositiveIntegerField(default=0, verbose_name="total points"),
                ),
                (
                    "lifetime_points",
                    models.PositiveIntegerField(
                        default=0, verbose_name="lifetime points"
                    ),
                ),
                (
                    "current_tier",
                    models.CharField(
                        choices=[
                            ("Bronze", "Bronze"),
                            ("Silver", "Silver"),
                            ("Gold", "Gold"),
                            ("Platinum", "Platinum"),
                            ("Diamond", "Diamond"),
                        ],
                        default="Bronze",
                        max_length=20,
                        verbose_name="current tier",
                    ),
                ),
                ("tier_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="point_summary",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "user point summary",
                "verbose_name_plural": "user point summaries",
            },
        ),
    ]
