# Generated by Django 5.2.8 on 2026-09-14 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_user_referral_code_closetpointtransaction_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userpointsummary",
            name="user",
        ),
        migrations.DeleteModel(
            name="ClosetPointTransaction",
        ),
        migrations.DeleteModel(
            name="UserPointSummary",
        ),
    ]
