# Generated by Django 5.2.8 on 2026-09-14 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_remove_userpointsummary_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="city",
            field=models.CharField(
                blank=True,
                help_text="User's city, district, or area",
                max_length=100,
                null=True,
                verbose_name="city / area",
            ),
        ),
    ]
