# Generated by Django 5.2.8 on 2026-09-14 09:53

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_user_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                help_text="User's profile picture",
                max_length=500,
                null=True,
                upload_to=users.models.profile_picture_upload_path,
                verbose_name="profile picture",
            ),
        ),
    ]
