# Generated by Django 5.2.8 on 2026-09-20 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_alter_user_profile_picture"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accountdeletionrequest",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Account Deletion Request",
                "verbose_name_plural": "Account Deletion Requests",
            },
        ),
        migrations.AddField(
            model_name="accountdeletionrequest",
            name="details",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="accountdeletionrequest",
            name="reason",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="accountdeletionrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("verified", "Verified"),
                    ("completed", "Completed"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
