# Generated by Django 5.2.8 on 2026-10-05 06:04

import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0012_security_and_gdpr_hardening"),
    ]

    operations = [
        migrations.CreateModel(
            name="Consent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("tos_privacy", "Terms of Service & Privacy Policy"),
                            ("photo_ai_processing", "Photo & AI Styling Processing"),
                            ("push_notification", "Push Notifications Opt-In"),
                            ("marketing", "Marketing Communications"),
                        ],
                        max_length=40,
                    ),
                ),
                ("granted", models.BooleanField(default=True)),
                (
                    "occurred_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "user_agent",
                    models.CharField(blank=True, default="", max_length=255),
                ),
            ],
            options={
                "verbose_name": "consent",
                "verbose_name_plural": "consents",
                "ordering": ["-occurred_at"],
            },
        ),
        migrations.CreateModel(
            name="DeletionJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "user_id",
                    models.UUIDField(
                        db_index=True, help_text="UUID of the target user"
                    ),
                ),
                (
                    "user_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("steps_done", models.JSONField(blank=True, default=list)),
                ("error_message", models.TextField(blank=True, default="")),
                (
                    "requested_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "deletion job",
                "verbose_name_plural": "deletion jobs",
                "ordering": ["-requested_at"],
            },
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "apns_token",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("ios", "Apple iOS (APNs)"),
                            ("android", "Google Android (FCM)"),
                        ],
                        default="ios",
                        max_length=20,
                    ),
                ),
                (
                    "prefs",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="User notification category preferences and quiet hours",
                    ),
                ),
                ("last_seen", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "device",
                "verbose_name_plural": "devices",
                "ordering": ["-last_seen"],
            },
        ),
        migrations.CreateModel(
            name="GdprAction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.UUIDField(db_index=True)),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("deletion_requested", "Deletion Requested"),
                            ("deletion_executed", "Deletion Executed"),
                            ("export_requested", "Export Requested"),
                            ("export_delivered", "Export Delivered"),
                        ],
                        max_length=40,
                    ),
                ),
                ("performed_by", models.CharField(default="user", max_length=50)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name": "GDPR action",
                "verbose_name_plural": "GDPR actions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Invite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=32, unique=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("standard", "Standard Invite"),
                            ("founding_member", "Founding Member"),
                            ("beta", "Beta Access"),
                            ("review", "App Review / TestFlight"),
                        ],
                        default="standard",
                        max_length=30,
                    ),
                ),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "invite",
                "verbose_name_plural": "invites",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Unique public username for handles and share links",
                max_length=30,
                null=True,
                unique=True,
                verbose_name="username",
            ),
        ),
        migrations.AddField(
            model_name="userpreference",
            name="blocked_brands",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of brand names the user dislikes or wishes to exclude",
                verbose_name="blocked brands",
            ),
        ),
        migrations.AddField(
            model_name="userpreference",
            name="clothing_sizes",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of clothing sizes (e.g. ['S', 'M'], ['38', '40'])",
                verbose_name="clothing sizes",
            ),
        ),
        migrations.AddField(
            model_name="userpreference",
            name="gender_prefs",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Target gender categories for styling (e.g. ['womenswear'], ['menswear'], ['all'])",
                verbose_name="gender preferences",
            ),
        ),
        migrations.AddField(
            model_name="userpreference",
            name="price_band",
            field=models.CharField(
                blank=True,
                choices=[
                    ("budget", "Budget / Affordable"),
                    ("mid_range", "Mid-Range / High Street"),
                    ("premium", "Premium & Contemporary"),
                    ("luxury", "Luxury & Designer"),
                ],
                default="mid_range",
                help_text="Target price tier for feeds and recommendations",
                max_length=20,
                verbose_name="price band",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("username"),
                condition=models.Q(("username__isnull", False)),
                name="unique_lower_username",
            ),
        ),
        migrations.AddField(
            model_name="consent",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consents",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="devices",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AddField(
            model_name="invite",
            name="owner_user",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created or owns this invite code",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_invites",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="invite",
            name="used_by",
            field=models.OneToOneField(
                blank=True,
                help_text="User who redeemed this invite",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="claimed_invite",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="consent",
            index=models.Index(
                fields=["user", "kind", "-occurred_at"],
                name="users_conse_user_id_2aabba_idx",
            ),
        ),
    ]
