# Generated by Django 5.2.8 on 2026-10-06 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_consent_deletionjob_device_gdpraction_invite_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="consent",
            name="version",
            field=models.CharField(blank=True, default="1.0", max_length=20),
        ),
    ]
