# Generated by Django 5.2.8 on 2026-10-08 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_consent_version"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="preferred_language",
            field=models.CharField(
                choices=[("de", "German"), ("en", "English")],
                default="en",
                help_text="User's preferred language for interface and notifications (de/en)",
                max_length=10,
            ),
        ),
    ]
