# Generated by Django 5.2.8 on 2026-09-14 06:03

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("closet", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="closetitem",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="price",
            ),
        ),
    ]
