# Generated by Django 5.2.8 on 2026-09-14 09:53

import closet.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("closet", "0002_alter_closetitem_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="closetitem",
            name="image",
            field=models.ImageField(
                blank=True,
                max_length=500,
                null=True,
                upload_to=closet.models.closet_item_upload_path,
                verbose_name="cloth picture",
            ),
        ),
    ]
