# Generated by Django 5.2.8 on 2026-10-06 08:37

import closet.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("closet", "0003_alter_closetitem_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="closetitem",
            name="currency",
            field=models.CharField(
                default="EUR", max_length=10, verbose_name="currency"
            ),
        ),
        migrations.AddField(
            model_name="closetitem",
            name="photo_sha256",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=64,
                verbose_name="photo SHA-256",
            ),
        ),
        migrations.AddField(
            model_name="closetitem",
            name="source",
            field=models.CharField(
                choices=[("manual", "Manual"), ("scan", "AI Scan")],
                default="manual",
                max_length=20,
                verbose_name="source",
            ),
        ),
        migrations.AddField(
            model_name="closetitem",
            name="style_vibe",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="style vibe"
            ),
        ),
        migrations.CreateModel(
            name="FitCheck",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "photo",
                    models.FileField(
                        blank=True,
                        max_length=500,
                        null=True,
                        upload_to=closet.models.fit_check_upload_path,
                        verbose_name="fit check photo",
                    ),
                ),
                (
                    "photo_sha256",
                    models.CharField(
                        db_index=True, max_length=64, verbose_name="photo SHA-256"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("queued", "Queued"),
                            ("tagged", "Tagged"),
                            ("dedupe_hit", "Dedupe Hit"),
                            ("failed", "Failed"),
                            ("nsfw_blocked", "NSFW Blocked"),
                        ],
                        default="uploaded",
                        max_length=30,
                        verbose_name="status",
                    ),
                ),
                (
                    "raw_tagging",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        null=True,
                        verbose_name="raw tagging data",
                    ),
                ),
                (
                    "tagging_model",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="tagging model",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "tagged_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="tagged at"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fit_checks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "fit check",
                "verbose_name_plural": "fit checks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="closetitem",
            name="fit_check",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="closet_items",
                to="closet.fitcheck",
                verbose_name="associated fit check",
            ),
        ),
        migrations.AddIndex(
            model_name="fitcheck",
            index=models.Index(
                fields=["user", "-created_at"], name="closet_fitc_user_id_67d126_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fitcheck",
            index=models.Index(
                fields=["user", "photo_sha256"], name="closet_fitc_user_id_02ab8c_idx"
            ),
        ),
    ]
