# Generated by Django 5.2.8 on 2026-10-06 09:23

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("closet", "0004_closetitem_currency_closetitem_photo_sha256_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="closetitem",
            name="attr_sentence_en",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="attribute sentence en",
            ),
        ),
        migrations.AddField(
            model_name="closetitem",
            name="confidence",
            field=models.FloatField(blank=True, null=True, verbose_name="confidence"),
        ),
        migrations.AddField(
            model_name="closetitem",
            name="fit",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="fit"
            ),
        ),
        migrations.AddField(
            model_name="closetitem",
            name="occasion",
            field=models.JSONField(blank=True, default=list, verbose_name="occasion"),
        ),
        migrations.AddField(
            model_name="closetitem",
            name="pattern",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="pattern"
            ),
        ),
        migrations.AddField(
            model_name="closetitem",
            name="style_tags",
            field=models.JSONField(blank=True, default=list, verbose_name="style tags"),
        ),
        migrations.AddField(
            model_name="fitcheck",
            name="cost_cents",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.0000"),
                max_digits=8,
                verbose_name="cost cents",
            ),
        ),
        migrations.AddField(
            model_name="fitcheck",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="deleted at"
            ),
        ),
        migrations.AddField(
            model_name="fitcheck",
            name="error_code",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="error code"
            ),
        ),
        migrations.AddField(
            model_name="fitcheck",
            name="nsfw_score",
            field=models.FloatField(blank=True, null=True, verbose_name="NSFW score"),
        ),
        migrations.AddField(
            model_name="fitcheck",
            name="provider",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="AI provider"
            ),
        ),
        migrations.AlterField(
            model_name="fitcheck",
            name="status",
            field=models.CharField(
                choices=[
                    ("uploaded", "Uploaded"),
                    ("queued", "Queued"),
                    ("processing", "Processing"),
                    ("tagged", "Tagged"),
                    ("dedupe_hit", "Dedupe Hit"),
                    ("failed", "Failed"),
                    ("failed_budget", "Failed Budget"),
                    ("nsfw_blocked", "NSFW Blocked"),
                ],
                default="uploaded",
                max_length=30,
                verbose_name="status",
            ),
        ),
        migrations.CreateModel(
            name="LLMCostLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "task",
                    models.CharField(
                        default="photo_analysis", max_length=50, verbose_name="task"
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        default="openai", max_length=50, verbose_name="provider"
                    ),
                ),
                ("model", models.CharField(max_length=100, verbose_name="model")),
                (
                    "input_tokens",
                    models.PositiveIntegerField(default=0, verbose_name="input tokens"),
                ),
                (
                    "output_tokens",
                    models.PositiveIntegerField(
                        default=0, verbose_name="output tokens"
                    ),
                ),
                (
                    "cost_cents",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        max_digits=8,
                        verbose_name="estimated cost (EUR cents)",
                    ),
                ),
                (
                    "latency_ms",
                    models.PositiveIntegerField(default=0, verbose_name="latency ms"),
                ),
                ("success", models.BooleanField(default=True, verbose_name="success")),
                (
                    "error_code",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="error code"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "fit_check",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cost_logs",
                        to="closet.fitcheck",
                        verbose_name="fit check",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="llm_cost_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "LLM cost log",
                "verbose_name_plural": "LLM cost logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="closet_llmc_user_id_2318ad_idx",
                    ),
                    models.Index(
                        fields=["task", "-created_at"],
                        name="closet_llmc_task_7a4644_idx",
                    ),
                ],
            },
        ),
    ]
