# Generated by Django 5.2.8 on 2026-07-21 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0003_index_updated_at'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='affiliateproduct',
            name='affiliate_a_aw_prod_41c418_idx',
        ),
        migrations.RenameIndex(
            model_name='affiliateproduct',
            new_name='affiliate_a_price_5ff5bc_idx',
            old_name='affiliate_a_price_idx',
        ),
        migrations.AddField(
            model_name='affiliateproduct',
            name='source',
            field=models.CharField(choices=[('awin', 'Awin'), ('rakuten', 'Rakuten')], db_index=True, default='awin', help_text='Which affiliate network this product comes from', max_length=20, verbose_name='affiliate source'),
        ),
        migrations.AlterField(
            model_name='affiliateproduct',
            name='aw_product_id',
            field=models.CharField(db_index=True, help_text='Unique product ID from Awin or Rakuten', max_length=100, unique=True, verbose_name='network product ID'),
        ),
        migrations.AlterField(
            model_name='affiliateproduct',
            name='brand',
            field=models.CharField(db_index=True, max_length=255, verbose_name='brand'),
        ),
        migrations.AlterField(
            model_name='affiliateproduct',
            name='category',
            field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='affiliateproduct',
            name='currency',
            field=models.CharField(default='GBP', max_length=10, verbose_name='currency'),
        ),
        migrations.AlterField(
            model_name='affiliateproduct',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='is active'),
        ),
    ]
