# Generated by Django 5.2.8 on 2026-09-21 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("affiliate", "0005_productfavorite"),
    ]

    operations = [
        migrations.AddField(
            model_name="affiliateproduct",
            name="additional_image_urls",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of additional product gallery images",
                verbose_name="additional image URLs",
            ),
        ),
    ]
