# Generated by Django 5.2.8 on 2026-10-06 04:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("affiliate", "0006_affiliateproduct_additional_image_urls"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="brand name"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=255, unique=True, verbose_name="brand slug"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("awin", "Awin"),
                            ("rakuten", "Rakuten"),
                            ("shopify_public", "Shopify Public"),
                            ("myc_feed", "MYC Feed"),
                        ],
                        default="awin",
                        max_length=30,
                        verbose_name="source kind",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="external ID (MID/Merchant ID)",
                    ),
                ),
                (
                    "feed_url",
                    models.URLField(
                        blank=True, default="", max_length=2000, verbose_name="feed URL"
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="brand configuration"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="EUR", max_length=10, verbose_name="currency"
                    ),
                ),
                (
                    "tier",
                    models.CharField(
                        choices=[("anchor", "Anchor"), ("indie", "Indie")],
                        default="indie",
                        max_length=20,
                        verbose_name="brand tier",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("applied", "Applied"),
                            ("live", "Live"),
                            ("paused", "Paused"),
                            ("ended", "Ended"),
                        ],
                        db_index=True,
                        default="live",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "consent_kind",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        verbose_name="consent kind",
                    ),
                ),
                (
                    "consent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="consent timestamp"
                    ),
                ),
                (
                    "consent_ref",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="consent reference",
                    ),
                ),
                (
                    "commission_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        verbose_name="commission percentage",
                    ),
                ),
                (
                    "validation_window_days",
                    models.PositiveIntegerField(
                        default=30, verbose_name="validation window (days)"
                    ),
                ),
                (
                    "last_sync_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last sync at"
                    ),
                ),
                (
                    "last_success_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last success at"
                    ),
                ),
                (
                    "fail_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="consecutive failure count"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "verbose_name": "brand",
                "verbose_name_plural": "brands",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CatalogSyncRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feed_id",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="feed identifier"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=30,
                        verbose_name="source network",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="started at"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="finished at"
                    ),
                ),
                (
                    "rows_seen",
                    models.PositiveIntegerField(default=0, verbose_name="rows seen"),
                ),
                (
                    "rows_new",
                    models.PositiveIntegerField(default=0, verbose_name="new rows"),
                ),
                (
                    "rows_changed",
                    models.PositiveIntegerField(default=0, verbose_name="changed rows"),
                ),
                (
                    "rows_unchanged",
                    models.PositiveIntegerField(
                        default=0, verbose_name="unchanged rows"
                    ),
                ),
                (
                    "rows_deactivated",
                    models.PositiveIntegerField(
                        default=0, verbose_name="deactivated rows"
                    ),
                ),
                (
                    "error_count",
                    models.PositiveIntegerField(default=0, verbose_name="error count"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("guarded", "Guarded (Safety threshold triggered)"),
                        ],
                        db_index=True,
                        default="running",
                        max_length=20,
                        verbose_name="sync status",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, default="", verbose_name="notes / logs"
                    ),
                ),
            ],
            options={
                "verbose_name": "catalog sync run",
                "verbose_name_plural": "catalog sync runs",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_class",
                    models.CharField(
                        choices=[
                            ("impression", "Impression"),
                            ("interaction", "Interaction"),
                            ("conversion", "Conversion"),
                        ],
                        db_index=True,
                        default="interaction",
                        max_length=30,
                        verbose_name="event class",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("impression", "Impression"),
                            ("detail_view", "Detail View"),
                            ("like", "Like"),
                            ("skip", "Skip"),
                            ("save", "Save"),
                            ("click_out", "Click Out (Buy)"),
                            ("favorite", "Favorite"),
                        ],
                        db_index=True,
                        max_length=30,
                        verbose_name="event type",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        default="for_you",
                        help_text="Surface where event occurred: for_you, newsfeed, detail, saved, sprint",
                        max_length=50,
                        verbose_name="source surface",
                    ),
                ),
                (
                    "feed_page",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="feed page number"
                    ),
                ),
                (
                    "dwell_ms",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="dwell time (ms)"
                    ),
                ),
                (
                    "berlin_day",
                    models.DateField(db_index=True, verbose_name="Berlin date"),
                ),
                (
                    "client_ts",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="client timestamp"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
            ],
            options={
                "verbose_name": "user behavior event",
                "verbose_name_plural": "user behavior events",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FeedAttributeMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        db_index=True,
                        default="all",
                        max_length=50,
                        verbose_name="source network",
                    ),
                ),
                (
                    "field",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="target field"
                    ),
                ),
                (
                    "raw_value",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="raw feed value"
                    ),
                ),
                (
                    "normalized_value",
                    models.CharField(max_length=255, verbose_name="normalized value"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "feed attribute mapping",
                "verbose_name_plural": "feed attribute mappings",
            },
        ),
        migrations.CreateModel(
            name="FeedImpressionsDaily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "berlin_day",
                    models.DateField(db_index=True, verbose_name="Berlin date"),
                ),
                (
                    "brand_name",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="brand name"
                    ),
                ),
                (
                    "impressions_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="viewed impressions count"
                    ),
                ),
                (
                    "detail_views_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="detail views count"
                    ),
                ),
                (
                    "saves_count",
                    models.PositiveIntegerField(default=0, verbose_name="saves count"),
                ),
                (
                    "clicks_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="click-outs count"
                    ),
                ),
                (
                    "likes_count",
                    models.PositiveIntegerField(default=0, verbose_name="likes count"),
                ),
                (
                    "skips_count",
                    models.PositiveIntegerField(default=0, verbose_name="skips count"),
                ),
            ],
            options={
                "verbose_name": "feed impressions daily",
                "verbose_name_plural": "feed impressions daily",
            },
        ),
        migrations.AddField(
            model_name="affiliateproduct",
            name="category_norm",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=255,
                verbose_name="normalized category",
            ),
        ),
        migrations.AddField(
            model_name="affiliateproduct",
            name="color_primary",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=100,
                verbose_name="primary color normalized",
            ),
        ),
        migrations.AddField(
            model_name="affiliateproduct",
            name="content_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="SHA-256 hash of core fields to avoid redundant DB writes on unchanged runs",
                max_length=64,
                verbose_name="payload content hash",
            ),
        ),
        migrations.AddField(
            model_name="affiliateproduct",
            name="first_seen_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="first seen at"
            ),
        ),
        migrations.AddField(
            model_name="affiliateproduct",
            name="gender",
            field=models.CharField(
                choices=[("women", "Women"), ("men", "Men"), ("unisex", "Unisex")],
                db_index=True,
                default="unisex",
                max_length=20,
                verbose_name="gender target",
            ),
        ),
        migrations.AddField(
            model_name="affiliateproduct",
            name="in_stock",
            field=models.BooleanField(
                db_index=True, default=True, verbose_name="in stock"
            ),
        ),
        migrations.AddField(
            model_name="affiliateproduct",
            name="last_seen_at",
            field=models.DateTimeField(
                blank=True, db_index=True, null=True, verbose_name="last seen at"
            ),
        ),
        migrations.AddField(
            model_name="affiliateproduct",
            name="miss_count",
            field=models.PositiveIntegerField(
                db_index=True,
                default=0,
                help_text="Number of consecutive sync runs where product was absent (2-run grace period)",
                verbose_name="consecutive missing sync runs",
            ),
        ),
        migrations.AddField(
            model_name="affiliateproduct",
            name="price_checked_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="price checked at"
            ),
        ),
        migrations.AddField(
            model_name="affiliateproduct",
            name="sizes",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of normalized available size strings",
                verbose_name="available sizes",
            ),
        ),
        migrations.AddField(
            model_name="productclick",
            name="click_ref",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                help_text="Unique click reference token passed to affiliate network for conversion attribution",
                null=True,
                verbose_name="click reference UUID",
            ),
        ),
        migrations.AddField(
            model_name="productclick",
            name="idempotency_key",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=100,
                verbose_name="idempotency key",
            ),
        ),
        migrations.AddField(
            model_name="productclick",
            name="ip_prefix",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Anonymized network prefix (e.g. /24 for IPv4, /48 for IPv6) — no raw PII",
                max_length=45,
                verbose_name="anonymized IP prefix",
            ),
        ),
        migrations.AddField(
            model_name="productclick",
            name="session_id",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="session ID"
            ),
        ),
        migrations.AddField(
            model_name="productclick",
            name="surface",
            field=models.CharField(
                db_index=True,
                default="feed",
                help_text="Surface where click originated: feed, newsfeed, detail, saved, dm, sprint",
                max_length=50,
                verbose_name="click surface",
            ),
        ),
        migrations.AddField(
            model_name="productclick",
            name="user_agent_hash",
            field=models.CharField(
                blank=True, default="", max_length=64, verbose_name="user agent hash"
            ),
        ),
        migrations.AlterField(
            model_name="affiliateproduct",
            name="aw_deep_link",
            field=models.URLField(
                help_text="Tracked affiliate URL template",
                max_length=2000,
                verbose_name="affiliate tracking link",
            ),
        ),
        migrations.AlterField(
            model_name="affiliateproduct",
            name="aw_product_id",
            field=models.CharField(
                db_index=True,
                help_text="Unique product ID from network or feed",
                max_length=100,
                unique=True,
                verbose_name="network product ID",
            ),
        ),
        migrations.AlterField(
            model_name="affiliateproduct",
            name="category",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, verbose_name="raw category"
            ),
        ),
        migrations.AlterField(
            model_name="affiliateproduct",
            name="currency",
            field=models.CharField(
                db_index=True, default="EUR", max_length=10, verbose_name="currency"
            ),
        ),
        migrations.AlterField(
            model_name="affiliateproduct",
            name="merchant_deep_link",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Direct link to product on brand website (fallback / direct UTM)",
                max_length=2000,
                verbose_name="merchant direct link",
            ),
        ),
        migrations.AlterField(
            model_name="affiliateproduct",
            name="source",
            field=models.CharField(
                choices=[
                    ("awin", "Awin"),
                    ("rakuten", "Rakuten"),
                    ("shopify", "Shopify"),
                    ("myc_feed", "MYC Feed"),
                ],
                db_index=True,
                default="awin",
                help_text="Which affiliate network or feed source this product comes from",
                max_length=20,
                verbose_name="affiliate source",
            ),
        ),
        migrations.AlterField(
            model_name="productclick",
            name="clicked_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="productclick",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="clicks",
                to="affiliate.affiliateproduct",
            ),
        ),
        migrations.AlterField(
            model_name="productfavorite",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="productfavorite",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="favorites",
                to="affiliate.affiliateproduct",
            ),
        ),
        migrations.AddIndex(
            model_name="productclick",
            index=models.Index(
                fields=["user", "clicked_at"], name="affiliate_p_user_id_12cca4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productclick",
            index=models.Index(
                fields=["product", "clicked_at"], name="affiliate_p_product_24bd6f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="brand",
            index=models.Index(
                fields=["status", "tier"], name="affiliate_b_status_1f1020_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="brand",
            index=models.Index(
                fields=["kind", "status"], name="affiliate_b_kind_fc3b7d_idx"
            ),
        ),
        migrations.AddField(
            model_name="affiliateproduct",
            name="brand_ref",
            field=models.ForeignKey(
                blank=True,
                help_text="Foreign key reference to registered Brand entity",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="affiliate.brand",
                verbose_name="brand reference",
            ),
        ),
        migrations.AddIndex(
            model_name="affiliateproduct",
            index=models.Index(
                fields=["category_norm", "is_active"],
                name="affiliate_a_categor_67da42_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="affiliateproduct",
            index=models.Index(
                fields=["gender", "is_active"], name="affiliate_a_gender_20c89b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="affiliateproduct",
            index=models.Index(
                fields=["currency", "is_active"], name="affiliate_a_currenc_52a197_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="affiliateproduct",
            index=models.Index(
                fields=["brand_ref", "is_active"], name="affiliate_a_brand_r_58fd4d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="affiliateproduct",
            index=models.Index(
                fields=["in_stock", "is_active"], name="affiliate_a_in_stoc_50c1d6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="affiliateproduct",
            index=models.Index(
                fields=["content_hash"], name="affiliate_a_content_a0de51_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="affiliateproduct",
            index=models.Index(
                fields=["source", "last_seen_at"], name="affiliate_a_source_165cd4_idx"
            ),
        ),
        migrations.AddField(
            model_name="catalogsyncrun",
            name="brand",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sync_runs",
                to="affiliate.brand",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="affiliate.affiliateproduct",
                verbose_name="product",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="affiliate_events",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="feedattributemapping",
            unique_together={("source", "field", "raw_value")},
        ),
        migrations.AddField(
            model_name="feedimpressionsdaily",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="daily_impressions",
                to="affiliate.affiliateproduct",
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["user", "created_at"], name="affiliate_e_user_id_9f3252_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["user", "event_type", "created_at"],
                name="affiliate_e_user_id_b97b21_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["product", "event_type"], name="affiliate_e_product_104e0d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["berlin_day", "event_type"],
                name="affiliate_e_berlin__aab190_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.UniqueConstraint(
                condition=models.Q(("event_type", "impression")),
                fields=("user", "product", "berlin_day", "event_type"),
                name="unique_user_product_day_impression",
            ),
        ),
        migrations.AddIndex(
            model_name="feedimpressionsdaily",
            index=models.Index(
                fields=["berlin_day", "brand_name"],
                name="affiliate_f_berlin__cb0550_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="feedimpressionsdaily",
            unique_together={("berlin_day", "product")},
        ),
    ]
