# Generated by Django 5.2.8 on 2026-10-06 05:40

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("affiliate", "0008_backfill_brands_and_click_ref"),
        ("rewards", "0002_rewardpointtransaction_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="affiliateproduct",
            name="cdn_image_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Locally stored/CDN replicated image URL (Audit CF-18)",
                max_length=2000,
                verbose_name="CDN replicated image URL",
            ),
        ),
        migrations.AddField(
            model_name="affiliateproduct",
            name="image_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="SHA-256 hash of image content for deduplication and integrity",
                max_length=64,
                verbose_name="image SHA-256 hash",
            ),
        ),
        migrations.AddField(
            model_name="affiliateproduct",
            name="image_replicated_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="image replicated at"
            ),
        ),
        migrations.CreateModel(
            name="Conversion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "conversion_id",
                    models.CharField(
                        db_index=True,
                        max_length=128,
                        verbose_name="network transaction ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("awin", "Awin"),
                            ("rakuten", "Rakuten"),
                            ("shopify", "Shopify"),
                        ],
                        db_index=True,
                        default="awin",
                        max_length=30,
                        verbose_name="affiliate source",
                    ),
                ),
                (
                    "click_ref",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Raw click reference token passed to network",
                        null=True,
                        verbose_name="click reference UUID",
                    ),
                ),
                (
                    "advertiser_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=100,
                        verbose_name="advertiser / merchant ID",
                    ),
                ),
                (
                    "order_reference",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=255,
                        verbose_name="merchant order reference",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("declined", "Declined"),
                            ("deleted", "Deleted"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=30,
                        verbose_name="conversion status",
                    ),
                ),
                (
                    "sale_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="sale amount",
                    ),
                ),
                (
                    "commission_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="commission amount",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        db_index=True,
                        default="EUR",
                        max_length=10,
                        verbose_name="currency code",
                    ),
                ),
                (
                    "transaction_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="transaction date"
                    ),
                ),
                (
                    "validation_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="validation date"
                    ),
                ),
                (
                    "reward_claimed",
                    models.BooleanField(
                        default=False, verbose_name="reward points claimed"
                    ),
                ),
                (
                    "raw_payload",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="raw webhook payload"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        help_text="Merchant brand associated with this transaction",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conversions",
                        to="affiliate.brand",
                    ),
                ),
                (
                    "click",
                    models.ForeignKey(
                        blank=True,
                        help_text="Linked outbound product click record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conversions",
                        to="affiliate.productclick",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        help_text="Purchased product in catalog if identifiable",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conversions",
                        to="affiliate.affiliateproduct",
                    ),
                ),
                (
                    "reward_transaction",
                    models.ForeignKey(
                        blank=True,
                        help_text="Linked reward transaction when purchase points are awarded",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="affiliate_conversions",
                        to="rewards.rewardpointtransaction",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who generated the click/conversion",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="affiliate_conversions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "affiliate conversion",
                "verbose_name_plural": "affiliate conversions",
                "ordering": ["-transaction_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["source", "status"],
                        name="affiliate_c_source_fd1810_idx",
                    ),
                    models.Index(
                        fields=["order_reference"],
                        name="affiliate_c_order_r_79bfe5_idx",
                    ),
                    models.Index(
                        fields=["click_ref"], name="affiliate_c_click_r_1e8812_idx"
                    ),
                    models.Index(
                        fields=["user", "status"], name="affiliate_c_user_id_de07f4_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source", "conversion_id"),
                        name="unique_source_conversion_id",
                    )
                ],
            },
        ),
    ]
