# Generated by Django 5.2.8 on 2026-09-14 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RewardPointTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("share_look", "Share a Look (+120)"),
                            ("invite_friend", "Invite Friends (+200)"),
                            ("make_purchase", "Make a Purchase (+200)"),
                            ("add_closet_item", "Add to Closet (+50)"),
                            ("custom_reward", "Custom Bonus Reward"),
                            ("points_expired", "Points Expired (-X)"),
                            ("redeem_reward", "Redeem Reward (-X)"),
                        ],
                        max_length=30,
                        verbose_name="action type",
                    ),
                ),
                ("points", models.IntegerField(verbose_name="points")),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="description"),
                ),
                (
                    "reference_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="reference id",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="expires at"
                    ),
                ),
                (
                    "is_expired",
                    models.BooleanField(default=False, verbose_name="is expired"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reward_transactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "reward point transaction",
                "verbose_name_plural": "reward point transactions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserRewardProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "available_points",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Spendable points that expire after 60 days",
                        verbose_name="available points",
                    ),
                ),
                (
                    "lifetime_points",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="All-time achievement points that dictate tier level; never decreases on expiration",
                        verbose_name="lifetime points",
                    ),
                ),
                (
                    "current_tier",
                    models.CharField(
                        choices=[
                            ("Bronze", "Bronze (0 - 2,000 pts)"),
                            ("Silver", "Silver (2,000 - 5,000 pts)"),
                            ("Gold", "Gold (5,000 - 10,000 pts)"),
                            ("Platinum", "Platinum (10,000 - 50,000 pts)"),
                            ("Diamond", "Diamond (50,000+ pts)"),
                        ],
                        default="Bronze",
                        max_length=20,
                        verbose_name="current tier",
                    ),
                ),
                ("tier_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reward_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "user reward profile",
                "verbose_name_plural": "user reward profiles",
            },
        ),
    ]
