# Generated by Django 5.2.8 on 2026-10-05 06:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rewards", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="rewardpointtransaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Activation"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="completed",
                max_length=20,
                verbose_name="status",
            ),
        ),
        migrations.AddConstraint(
            model_name="rewardpointtransaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("action_type", "invite_friend"),
                    models.Q(("reference_id", ""), _negated=True),
                ),
                fields=("action_type", "reference_id"),
                name="unique_invite_friend_reward_reference",
            ),
        ),
    ]
