# Generated by Django 5.2.8 on 2026-10-07 05:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rewards", "0002_rewardpointtransaction_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="rewardpointtransaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("action_type", "make_purchase"),
                    models.Q(("reference_id", ""), _negated=True),
                ),
                fields=("action_type", "reference_id"),
                name="unique_make_purchase_reward_reference",
            ),
        ),
    ]
