# Generated by Django 5.2.8 on 2026-10-07 06:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "rewards",
            "0003_rewardpointtransaction_unique_make_purchase_reward_reference",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="rewardpointtransaction",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("share_look", "Share a Look (+120)"),
                    ("invite_friend", "Invite Friends (+200)"),
                    ("make_purchase", "Make a Purchase (+200)"),
                    ("add_closet_item", "Add to Closet (+50)"),
                    ("custom_reward", "Custom Bonus Reward"),
                    ("points_expired", "Points Expired (-X)"),
                    ("points_reversal", "Activity Points Reversal (-X)"),
                    ("redeem_reward", "Redeem Reward (-X)"),
                ],
                max_length=30,
                verbose_name="action type",
            ),
        ),
        migrations.AlterField(
            model_name="userrewardprofile",
            name="available_points",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Spendable points that expire after 24 months",
                verbose_name="available points",
            ),
        ),
        migrations.CreateModel(
            name="LedgerAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("user_available", "User Available Balance"),
                            ("points_liability_control", "Points Liability Control"),
                            ("awin_receivable", "AWIN Affiliate Receivable"),
                            ("boutique_receivable", "Boutique Receivable"),
                            ("commission_revenue", "Commission Revenue"),
                            (
                                "marketing_expense",
                                "Marketing / Referral / Activity Expense",
                            ),
                            ("redemption_clearing", "Redemption Clearing"),
                            ("breakage_income", "Breakage / Expiration Income"),
                            ("fraud_writeoff", "Fraud Write-off"),
                        ],
                        max_length=40,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ledger_accounts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "ledger account",
                "verbose_name_plural": "ledger accounts",
            },
        ),
        migrations.CreateModel(
            name="LedgerTxn",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("txn_type", models.CharField(max_length=50)),
                (
                    "conversion_reference",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("idempotency_key", models.CharField(max_length=150, unique=True)),
                ("description", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_ledger_txns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "ledger transaction",
                "verbose_name_plural": "ledger transactions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LedgerEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("points", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="rewards.ledgeraccount",
                    ),
                ),
                (
                    "txn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="rewards.ledgertxn",
                    ),
                ),
            ],
            options={
                "verbose_name": "ledger entry",
                "verbose_name_plural": "ledger entries",
            },
        ),
        migrations.CreateModel(
            name="PointAward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "award_type",
                    models.CharField(
                        choices=[
                            ("purchase_awin", "Purchase AWIN Conversion"),
                            ("purchase_boutique", "Purchase Boutique Partner"),
                            ("referral_signup", "Referral Signup"),
                            ("referral_active", "Referral Activated"),
                            ("weekly_goal", "Weekly Goal"),
                            ("share_look", "Share Look Outfit"),
                            ("add_closet_item", "Add Closet Item"),
                            ("manual_goodwill", "Manual Goodwill Credit"),
                        ],
                        max_length=30,
                    ),
                ),
                ("points_original", models.PositiveIntegerField()),
                ("points_current", models.PositiveIntegerField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("RESERVED", "Reserved (Unverified Intent)"),
                            ("PENDING", "Pending Postback / Advertiser Review"),
                            ("CONFIRMED", "Confirmed (Approved)"),
                            ("AVAILABLE", "Available for Spending"),
                            ("PARTIALLY_REDEEMED", "Partially Redeemed"),
                            ("REDEEMED", "Fully Redeemed"),
                            ("VOID", "Voided / Cancelled"),
                            ("CLAWED_BACK", "Clawed Back / Reversal"),
                            ("EXPIRED", "Expired (24 Months)"),
                        ],
                        default="AVAILABLE",
                        max_length=25,
                    ),
                ),
                (
                    "click_reference",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "conversion_reference",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "outfit_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                ("eta_available_at", models.DateTimeField(blank=True, null=True)),
                ("available_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "referred_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="referred_awards_generated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="referred user",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="point_awards",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="recipient user",
                    ),
                ),
            ],
            options={
                "verbose_name": "point award",
                "verbose_name_plural": "point awards",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="ledgertxn",
            name="award",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ledger_transactions",
                to="rewards.pointaward",
            ),
        ),
        migrations.CreateModel(
            name="AwardStateLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_state", models.CharField(max_length=25)),
                ("to_state", models.CharField(max_length=25)),
                ("reason", models.CharField(blank=True, default="", max_length=255)),
                ("points_delta", models.IntegerField(default=0)),
                ("actor", models.CharField(default="system", max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "award",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="state_logs",
                        to="rewards.pointaward",
                    ),
                ),
            ],
            options={
                "verbose_name": "award state log",
                "verbose_name_plural": "award state logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="ledgeraccount",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("kind", "user_available"), ("user__isnull", False)),
                    models.Q(
                        models.Q(("kind", "user_available"), _negated=True),
                        ("user__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="ledger_account_user_kind_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="ledgeraccount",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", False)),
                fields=("kind", "user"),
                name="unique_user_ledger_account",
            ),
        ),
        migrations.AddConstraint(
            model_name="ledgeraccount",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", True)),
                fields=("kind",),
                name="unique_system_ledger_account",
            ),
        ),
        migrations.AddConstraint(
            model_name="ledgerentry",
            constraint=models.CheckConstraint(
                condition=models.Q(("points", 0), _negated=True),
                name="ledger_entry_points_nonzero",
            ),
        ),
        migrations.AddConstraint(
            model_name="pointaward",
            constraint=models.UniqueConstraint(
                condition=models.Q(("conversion_reference", ""), _negated=True),
                fields=("conversion_reference",),
                name="unique_point_award_conversion",
            ),
        ),
        migrations.AddConstraint(
            model_name="pointaward",
            constraint=models.UniqueConstraint(
                condition=models.Q(("referred_user__isnull", False)),
                fields=("award_type", "referred_user"),
                name="unique_point_award_referred_user",
            ),
        ),
    ]
