# Generated by Django 5.2.8 on 2026-09-14 09:53

import social.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0003_delete_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todayoutfit",
            name="image",
            field=models.ImageField(
                max_length=500,
                upload_to=social.models.today_outfit_upload_path,
                verbose_name="outfit picture",
            ),
        ),
    ]
