# Generated by Django 5.2.8 on 2026-09-15 09:25

import django.db.models.deletion
import social.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("affiliate", "0004_add_source_field"),
        ("social", "0004_alter_todayoutfit_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StoryLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StoryView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("viewed_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-viewed_at"],
            },
        ),
        migrations.AddField(
            model_name="directmessage",
            name="image",
            field=models.ImageField(
                blank=True,
                max_length=500,
                null=True,
                upload_to=social.models.chat_attachment_upload_path,
            ),
        ),
        migrations.AddField(
            model_name="directmessage",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("text", "Text Message"),
                    ("image", "Image Attachment"),
                    ("product", "Shared Product"),
                    ("outfit", "Shared Outfit"),
                    ("story_reply", "Story Reply"),
                ],
                default="text",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="directmessage",
            name="shared_outfit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shared_in_messages",
                to="social.todayoutfit",
            ),
        ),
        migrations.AddField(
            model_name="directmessage",
            name="shared_product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shared_in_messages",
                to="affiliate.affiliateproduct",
            ),
        ),
        migrations.AlterField(
            model_name="directmessage",
            name="content",
            field=models.TextField(
                blank=True, default="", verbose_name="message content"
            ),
        ),
        migrations.CreateModel(
            name="Story",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        max_length=500,
                        upload_to=social.models.story_image_upload_path,
                        verbose_name="story picture",
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, default="", max_length=500, verbose_name="caption"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="expires at"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="is active"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stories",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "story",
                "verbose_name_plural": "stories",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="directmessage",
            name="story_reference",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="replied_in_messages",
                to="social.story",
            ),
        ),
        migrations.AddIndex(
            model_name="directmessage",
            index=models.Index(
                fields=["sender", "recipient", "created_at"],
                name="social_dire_sender__653aee_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="directmessage",
            index=models.Index(
                fields=["recipient", "is_read"], name="social_dire_recipie_6ab22f_idx"
            ),
        ),
        migrations.AddField(
            model_name="storylike",
            name="story",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to="social.story",
            ),
        ),
        migrations.AddField(
            model_name="storylike",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="liked_stories",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="storyview",
            name="story",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="views",
                to="social.story",
            ),
        ),
        migrations.AddField(
            model_name="storyview",
            name="viewer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="viewed_stories",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="story",
            index=models.Index(
                fields=["user", "is_active", "-created_at"],
                name="social_stor_user_id_c86fe0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="story",
            index=models.Index(
                fields=["expires_at", "is_active"],
                name="social_stor_expires_041284_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="storylike",
            unique_together={("story", "user")},
        ),
        migrations.AlterUniqueTogether(
            name="storyview",
            unique_together={("story", "viewer")},
        ),
    ]
