# Generated by Django 5.2.8 on 2026-09-19 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0005_storylike_storyview_directmessage_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="todayoutfit",
            name="style_category",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="style category"
            ),
        ),
        migrations.AddField(
            model_name="todayoutfit",
            name="weather_tag",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="weather tag"
            ),
        ),
    ]
