# Generated by Django 5.2.8 on 2026-09-19 03:38

import django.db.models.deletion
import social.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("closet", "0003_alter_closetitem_image"),
        ("social", "0006_todayoutfit_style_category_todayoutfit_weather_tag"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OutfitImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        max_length=500,
                        upload_to=social.models.today_outfit_upload_path,
                        verbose_name="outfit picture",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="display order"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "outfit image",
                "verbose_name_plural": "outfit images",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="todayoutfit",
            index=models.Index(
                fields=["visibility", "-created_at"],
                name="social_toda_visibil_091632_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="todayoutfit",
            index=models.Index(
                fields=["user", "visibility", "-created_at"],
                name="social_toda_user_id_8d09b2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="todayoutfit",
            index=models.Index(
                fields=["style_category", "visibility", "-created_at"],
                name="social_toda_style_c_ff1d71_idx",
            ),
        ),
        migrations.AddField(
            model_name="outfitimage",
            name="outfit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="social.todayoutfit",
                verbose_name="outfit",
            ),
        ),
        migrations.AddIndex(
            model_name="outfitimage",
            index=models.Index(
                fields=["outfit", "order"], name="social_outf_outfit__ec8e08_idx"
            ),
        ),
    ]
