# Generated by Django 5.2.8 on 2026-10-07 05:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0007_outfitimage_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("outfit", "Today Outfit"),
                            ("story", "Story"),
                            ("user", "User Profile"),
                            ("message", "Direct Message"),
                        ],
                        max_length=20,
                    ),
                ),
                ("target_id", models.CharField(max_length=100)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("spam", "Spam / Commercial advertising"),
                            ("harassment", "Harassment / Hate speech"),
                            ("nudity", "Nudity / Sexual content"),
                            ("violence", "Violence / Self-harm"),
                            ("copyright", "Copyright infringement"),
                            ("impersonation", "Impersonation"),
                            ("other", "Other violation"),
                        ],
                        max_length=30,
                    ),
                ),
                ("details", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("investigating", "Investigating"),
                            ("resolved", "Action Taken"),
                            ("dismissed", "Dismissed / False Report"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("moderator_notes", models.TextField(blank=True, default="")),
                (
                    "action_taken",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submitted_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "content report",
                "verbose_name_plural": "content reports",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="social_cont_status_6afb58_idx",
                    ),
                    models.Index(
                        fields=["target_type", "target_id"],
                        name="social_cont_target__87720f_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "blocked",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocked_by_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "blocker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocking_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "user block",
                "verbose_name_plural": "user blocks",
                "indexes": [
                    models.Index(
                        fields=["blocker", "blocked"],
                        name="social_user_blocker_5ae552_idx",
                    )
                ],
                "unique_together": {("blocker", "blocked")},
            },
        ),
    ]
