# Generated by Django 5.2.8 on 2026-09-14 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("outfit_like", "Outfit Liked"),
                            ("new_follower", "New Follower"),
                            ("direct_message", "Direct Message"),
                            ("points_earned", "Points Earned"),
                            ("points_expired", "Points Expired"),
                            ("tier_upgrade", "Tier Upgrade"),
                            ("system", "System Announcement"),
                        ],
                        max_length=30,
                        verbose_name="notification type",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                ("message", models.TextField(verbose_name="message")),
                (
                    "data",
                    models.JSONField(blank=True, default=dict, verbose_name="data"),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="is read")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="recipient",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="sender",
                    ),
                ),
            ],
            options={
                "verbose_name": "notification",
                "verbose_name_plural": "notifications",
                "ordering": ["-created_at"],
            },
        ),
    ]
