# Generated by Django 5.2.8 on 2026-09-22 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("outfit_like", "Outfit Liked"),
                    ("new_follower", "New Follower"),
                    ("direct_message", "Direct Message"),
                    ("points_earned", "Points Earned"),
                    ("points_expired", "Points Expired"),
                    ("tier_upgrade", "Tier Upgrade"),
                    ("closet_item_added", "Closet Item Added"),
                    ("outfit_shared", "Outfit Shared"),
                    ("story_reaction", "Story Reaction"),
                    ("system", "System Announcement"),
                ],
                max_length=30,
                verbose_name="notification type",
            ),
        ),
    ]
